language: node_js
sudo: false
node_js:
- '0.10'
before_script: ./node_modules/.bin/gulp
deploy:
  provider: s3
  access_key_id: AKIAJH2D5IPIRHYJT5IA
  secret_access_key:
    secure: "J1Yo/vN2bA1+7hmeXtjityRLiEXbBKzBjz0fDX1adNgK4RfiYS7X4V3O4SuZ1DkpS5krxrrl4OcajLQxAvRBHo42WkXHf3cdrbQJoxikU2mWTVKTLeAXdhowpxjhypqGmotBMifajdB+2ToZNmI8xbnR3G4wYSyZX+ngtPQjolw="
  bucket: blu.octoblu.com
  endpoint: blu.octoblu.com.s3-website-us-west-2.amazonaws.com
  region: us-west-2
  local-dir: public
  skip_cleanup: true
  acl: public_read
  on:
    branch: master
